apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ops-web.name" . }}
  labels:
    app: {{ include "ops-web.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ops-web.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ops-web.name" . }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-text={{ .Values.message }}"
            - "-listen=:8080"
          ports:
            - containerPort: 8080
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
